### ISSUE TITLE
Support custom formats option

### ISSUE THREAD

**Issue by Bluscream** [ammarlakis/action-ajv#1]
https://ajv.js.org/options.html#formats

i tried this:

```yaml
      - name: Validate manifest.json
        uses: ammarlakis/action-ajv@master
        with:
          data: manifest.json
          schema: schemas/manifest.schema.json
          strictSchema: "log"
          formats:
            "boolean":  "/(true|false|0|1|yes|no|enabled|disabled|on|off)/ig"
```

which results in

```

Invalid workflow file: .github/workflows/validate-ammarlakis.yml#L22
The workflow is not valid. .github/workflows/validate-ammarlakis.yml (Line: 22, Col: 13): A mapping was not expected .github/workflows/validate-ammarlakis.yml (Line: 30, Col: 13): A mapping was not expected

```
