### ISSUE TITLE
[bug] Validation fails even with everything disabled

### ISSUE THREAD

**Issue by Bluscream** [ammarlakis/action-ajv#2]
https://github.com/Bluscream/AMPTemplates/actions/runs/10443146876
> Failed to validate: unknown format "boolean" ignored in schema at path "#/properties/App_RapidStartup"

it even says it "ignored" the unknown format, yet it kills the action

```
      - name: Validate *.generator.json
        uses: ammarlakis/action-ajv@master
        with:
          data: '*.generator.json'
          schema: schemas/generator.schema.json
          strict: false
          validateFormats: false
          allErrors: true
          verbose: true
```
